# Copyright Louis Dionne 2015
# Copyright Gonzalo Brito Gadeschi 2015
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

language: c++
os: linux
sudo: false

matrix:
  include:
    # debug build
    - env: COMPILER=clang++-3.8 BUILD_TYPE=Debug
      addons: &clang
        apt:
          packages: ["clang-3.8", "clang-format-3.8", "valgrind", "python-yaml", "lcov", "libopenmpi-dev", "openmpi-bin" ]
          sources: &sources ["ubuntu-toolchain-r-test", "llvm-toolchain-precise"]

    # release build + valgrind
    - env: COMPILER=clang++-3.8 BUILD_TYPE=Release Valgrind=true
      addons: *clang

# Coverage and site generation job
#
# We define it here instead of in matrix.include because otherwise we end up
# with a job without environment variables within the matrix.
env:
  global:
    # GitHub token for pushing the documentation, logging in with the
    # Travis command line utility and so on. The token is stored in the
    # ${GH_TOKEN} environment variable.
    - secure: "QKmAzwG8jeQV1GMEqNIZlKy5yB4+L/ecFxDAHa0XYPnD5d+IP3PT+DLyD36THVA9DmGqWLJWlMc27mZghjH/W/dvNtNoQjEr6GOhUTqUjK2dAvjEKd23VNg/qUr7I8i0MNPK4dgOuKXzGDKK/tj7i294T8pAS1BlKmF7dHtZjmvaMg9VoSaXtWwO8JxgfrvMf0ruDV7iRgkhhuCUa/qzwSzShL1wbXbdtNqvmYodc7aBh/wX5COznldGBDCK0TZbjnvL9Bbr+bvrclmrTcuDL55tl0Bdyags1V6tw0NzwUXJACDXnQ9MknqNCbkMlBys+/6tBbqFi5nJJgvRIrkxGm1gFHePrhesEB7yScTj6HjtOOWF8UnV9Y8098o/Q4TaPAJoVaVuNkfpG/rxng5VWCD+W97w6bUr0QJyVjHQcdIe924GguLx28lrJTfDcg4Ej7osu5wmd9iCWdL/hsgTyT6gm4Im05k0o60I8uyJ1zQ1YIZg8xl/tveuTs4/Q4ZVhHdOMPjawXT+cQIdq1BfPzaRq6Uce7BvjRQpBolxyz/GzMG0pRunfk0uHiV6sIPGp66dhlq8Ff/7Vdrg1kpXTJKR6KMFA+IVQiX50XjFoqMdTXxx/NjLGQ4JMsKz6sg4tyS6atCH3niOuZffZewxikR/CJpdU2i+2ksfmF6rr8E="
  matrix:
    - COMPILER=clang++-3.8 BUILD_TYPE=Debug Coverage=true Site=true
    
addons: *clang
 
install:
  # All the dependencies are installed to the deps/ subdirectory.
  - DEPS_DIR="${PWD}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  # Install a recent CMake
  - CMAKE_URL=http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
  - mkdir cmake
  - travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${PWD}/cmake/bin:${PATH}

  # Install libc++ and libc++abi
  - |
    if [[ "${COMPILER}" =~ clang.+ ]]; then
        LLVM_URL="https://github.com/llvm-mirror/llvm/archive/master.tar.gz"
        LIBCXX_URL="https://github.com/llvm-mirror/libcxx/archive/master.tar.gz"
        LIBCXXABI_URL="https://github.com/llvm-mirror/libcxxabi/archive/master.tar.gz"
        TAR_FMT="-xz"
        mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
        travis_retry wget --quiet -O - ${LLVM_URL} | tar --strip-components=1 ${TAR_FMT} -C llvm
        travis_retry wget --quiet -O - ${LIBCXX_URL} | tar --strip-components=1 ${TAR_FMT} -C llvm/projects/libcxx
        travis_retry wget --quiet -O - ${LIBCXXABI_URL} | tar --strip-components=1 ${TAR_FMT} -C llvm/projects/libcxxabi
        (cd llvm/build && cmake .. -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && make cxx -j2)
        cd ${DEPS_DIR}
    fi

  # Install a recent Doxygen
  - |
    if [[ "${Site}" == "true" ]]; then
        DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.linux.bin.tar.gz"
        mkdir ${DEPS_DIR}/doxygen && travis_retry wget --quiet -O - ${DOXYGEN_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/doxygen
        export PATH=${DEPS_DIR}/doxygen/bin:${PATH}
    fi

  # Install Boost headers
  - BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz"
  - mkdir boost && travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C boost

  # Install docopt 
  - pip install --user docopt

before_script:
  # Go back to the root of the project.
  - cd ${TRAVIS_BUILD_DIR}

  # Set the git identity (for pushing the documentation and the benchmarks)
  - git config --global user.name "Travis bot"

  # Check baseline memory usage; useful to know when OOMs occur
  - free
  - vmstat
  - ps aux --sort=-rss | head -n 10

  # Valgrind in Travis VMs does not support anything higher than SSE 4.2 
  # This disables -march=native which is typically higher and forces SSE 4.2 instead
  - sed -i 's/march=native/msse4.2/' cmake/hm3_compiler_flags.cmake

  # Setup the build directory
  - mkdir build
  - cd build
  # Export the path to libc++
  - |
    if [[ "${COMPILER}" =~ clang.+ ]]; then
        export CXXFLAGS="-I ${DEPS_DIR}/llvm/build/include/c++/v1"
        export LDFLAGS="-L ${DEPS_DIR}/llvm/build/lib -l c++ -l c++abi"
        export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/llvm/build/lib"
    fi

  # Configure the build
  # --debug-output
  - CMAKE_VARIABLES="-Wdev -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DHM3_ENABLE_WERROR=On -DHM3_ENABLE_PARAVIEW_PLUGINS=Off -DHM3_VERBOSE_CONFIGURE=On -DCMAKE_CXX_FLAGS="-DHM3_DISABLE_MPI_SIZED_DATATYPES" -DBOOST_ROOT=${DEPS_DIR}/boost"
  - |
    if [[ "${BUILD_TYPE}" == "Debug" ]]; then
      CMAKE_VARIABLES="${CMAKE_VARIABLES} -DHM3_ENABLE_ASSERTIONS=ON -DHM3_ENABLE_DEBUG_INFO=ON"
    fi
  - |
    if [[ "${ASan}" == "true" ]]; then
      CMAKE_VARIABLES="${CMAKE_VARIABLES} -DHM3_ENABLE_ASAN=ON"
    fi
  - |
    if [[ "${Coverage}" == "true" ]]; then
      CMAKE_VARIABLES="${CMAKE_VARIABLES} -DHM3_ENABLE_COVERAGE=ON"
    fi
  - cmake .. $CMAKE_VARIABLES

script:
  # Build the documentation:
  - if [[ "${Site}" == "true" ]]; then make doc; fi
  # Build and run the unit tests and examples:
  - make check -k -j 2
  - if [[ "${Valgrind}" == "true" ]]; then ctest -VV -D ExperimentalMemCheck; fi

after_success:
  # Update coveralls:
  # - download and install lcov, and coveralls-lcov.
  # - run lcov to generate coverage report
  # - strip test/ and example/ subdirectories from coverage report
  # - upload report to coveralls
  - |
    if [[ "${Coverage}" == "true" ]]; then
        gem install coveralls-lcov
        lcov --directory ./ --base-directory ./ --capture --output-file coverage.info
        lcov --remove coverage.info "/usr*" "*/hm3/test/*" "*/hm3/example/*" "*/hm3/build/*" "*/hm3/deps/*"  -o coverage.info
        coveralls-lcov coverage.info
    fi

  # Update the documentation
  - |
    if [[ "${Site}" == "true" && "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        doxygen --version
        #make gh-pages.update
        make gh-pages.push &>/dev/null
    fi

notifications:
  email: false
