HM3: hm3::io::client Struct Reference
hm3::io::client Struct Reference
Description
Helps a single file group interact with an io::session.
Public Member Functions
client (io::session &s, string name)
Read client name from sesion s.
client (io::session &s, string const &name, string const &type, string const &dependency=string{})
Registers client with the session.
io::session & session ()
Returns a reference to the underlying io::session.
io::session const & session () const
Returns a reference to the underlying io::session.
string const & name () const
Client name.
string const & type () const
Client type.
bool has_dependency () const
Has the client a dependency.
string const & dependency () const
Client dependency name.
io::file new_file () const
Empty file for the file group.
void write (io::file &f)
Write file.
io::file::index_t no_files () const
Number of files for this group in the session.
io::file get_file (io::file::index_t i=io::file::index_t{}) const
Get the file with index i to read it (by default returns the last file)
Member Function Documentation
void hm3::io::client::write (io::file & f)
Write file.
Note: f should have been obtained from a call to file().
References hm3::io::file::group_name(), session(), and hm3::io::session::write().