HM3: hm3::math::math_detail::floating_point< RawType > Struct Template Reference
hm3::math::math_detail::floating_point< RawType > Struct Template Reference
Description
template<typename RawType>
struct hm3::math::math_detail::floating_point< RawType >
This template class represents an IEEE floating-point number (either single-precision or double-precision, depending on the template parameters).
The purpose of this class is to do more sophisticated number comparison. (Due to round-off error, etc, it's very unlikely that two floating-points will be equal exactly. Hence a naive comparison by the == operation often doesn't work.)
Format of IEEE floating-point:
The most-significant bit being the leftmost, an IEEE floating-point looks like
sign_bit exponent_bits fraction_bits
Here, sign_bit is a single bit that designates the sign of the number.
For float, there are 8 exponent bits and 23 fraction bits.
For double, there are 11 exponent bits and 52 fraction bits.
More details can be found at http://en.wikipedia.org/wiki/IEEE_floating-point_standard.
Template parameter:
Template Parameters
RawType The raw floating-point type (either float or double)
Public Types
using Bits = typename type_with_size< sizeof(RawType)>::UInt
Defines the unsigned integer type that has the same size as the floating point number.
Public Member Functions
constexpr floating_point (const RawType &x) noexcept
Constructs a floating_point from a raw floating-point number.
constexpr const Bits & bits () const noexcept
Non-static methods.
constexpr Bits exponent_bits () const noexcept
Returns the exponent bits of this number.
constexpr Bits fraction_bits () const noexcept
Returns the fraction bits of this number.
constexpr Bits sign_bit () const noexcept
Returns the sign bit of this number.
constexpr bool is_nan () const noexcept
Returns true iff this is NAN (not a number).
constexpr bool almost_equals (const floating_point &rhs) const noexcept
Returns true iff this number is at most k_max_ulps ULP's away from rhs. In particular, this function:
Static Public Member Functions
static constexpr RawType reinterpret_bits (const Bits bits) noexcept
Static methods.
static constexpr RawType infinity () noexcept
Returns the floating-point number that represent positive infinity.
Static Public Attributes
static const constexpr std::size_t k_bit_count = 8 * sizeof(RawType)
Constants.
static const constexpr std::size_t k_fraction_bit_count = std::numeric_limits<RawType>::digits - 1
of fraction bits in a number.
static const constexpr std::size_t k_exponent_bit_count = k_bit_count - 1 - k_fraction_bit_count
of exponent bits in a number.
static const constexpr Bits k_sign_bit_mask
The mask for the sign bit.
static const constexpr Bits k_exponent_bit_mask = ~(k_sign_bit_mask | k_fraction_bit_mask)
The mask for the exponent bits.
static const constexpr std::size_t k_max_ulps = 4
How many ULP's (Units in the Last Place) we want to tolerate when comparing two numbers. The larger the value, the more error we allow. A 0 value means that two numbers must be exactly the same to be considered equal.
Member Function Documentation
template<typename RawType > static constexpr RawType hm3::math::math_detail::floating_point< RawType >::reinterpret_bits (const Bits bits) static noexcept
Static methods.
Reinterprets a bit pattern as a floating-point number.
This function is needed to test the almost_equals() method.
References hm3::math::math_detail::floating_point< RawType >::bits().
Referenced by hm3::math::math_detail::floating_point< RawType >::infinity().
template<typename RawType > constexpr const Bits& hm3::math::math_detail::floating_point< RawType >::bits () const noexcept
Non-static methods.
Returns the bits that represents this number.
Referenced by hm3::math::math_detail::floating_point< RawType >::reinterpret_bits().
template<typename RawType > constexpr bool hm3::math::math_detail::floating_point< RawType >::is_nan () const noexcept
Returns true iff this is NAN (not a number).
It's a NAN if the exponent bits are all ones and the fraction bits are not entirely zeros.
References hm3::math::math_detail::floating_point< RawType >::exponent_bits(), hm3::math::math_detail::floating_point< RawType >::fraction_bits(), and hm3::math::math_detail::floating_point< RawType >::k_exponent_bit_mask.
Referenced by hm3::math::math_detail::floating_point< RawType >::almost_equals().
template<typename RawType > constexpr bool hm3::math::math_detail::floating_point< RawType >::almost_equals (const floating_point< RawType > & rhs) const noexcept
Returns true iff this number is at most k_max_ulps ULP's away from rhs. In particular, this function:
returns false if either number is (or both are) NAN.
treats really large numbers as almost equal to infinity.
thinks +0.0 and -0.0 are 0 DLP's apart.
The IEEE standard says that any comparison operation involving a NAN must return false.
References hm3::math::math_detail::floating_point< RawType >::is_nan(), and hm3::math::math_detail::floating_point< RawType >::k_max_ulps.
Member Data Documentation
template<typename RawType > const constexpr std::size_t hm3::math::math_detail::floating_point< RawType >::k_bit_count = 8 * sizeof(RawType) static
Constants.
of bits in a number.
template<typename RawType > const constexpr std::size_t hm3::math::math_detail::floating_point< RawType >::k_max_ulps = 4 static
How many ULP's (Units in the Last Place) we want to tolerate when comparing two numbers. The larger the value, the more error we allow. A 0 value means that two numbers must be exactly the same to be considered equal.
The maximum error of a single floating-point operation is 0.5 units in the last place. On Intel CPU's, all floating-point calculations are done with 80-bit precision, while double has 64 bits. Therefore, 4 should be enough for ordinary use.
See the following article for more details on ULP: http://www.cygnus-software.com/papers/comparingfloats/comparingfloats.htm.
Referenced by hm3::math::math_detail::floating_point< RawType >::almost_equals().
Constructor & Destructor Documentation
template<typename RawType > constexpr hm3::math::math_detail::floating_point< RawType >::floating_point (const RawType & x) explicit noexcept
Constructs a floating_point from a raw floating-point number.
On an Intel CPU, passing a non-normalized NAN (Not a Number) around may change its bits, although the new value is guaranteed to be also a NAN. Therefore, don't expect this constructor to preserve the bits in x when x is a NAN.