HM3: hm3::grid::hc::single< Nd > Struct Template Reference
hm3::grid::hc::single< Nd > Struct Template Reference
Description
template<uint_t Nd>
struct hm3::grid::hc::single< Nd >
Hierarchical Cartesian grid.
Public Member Functions
auto bounding_box () const noexcept
Bounding box of the grid (root node geometry)
num_t length (level_idx l) const noexcept
Length of node at level l.
num_t length (tree_node_idx n) const noexcept
Length of node n.
point_t coordinates (tree_node_idx n) const noexcept
Center coordinates of node n.
node_t node (tree_node_idx n) const noexcept
Node at index n.
geometry::square< Nd > geometry (tree_node_idx n) const noexcept
Geometry of node n.
level_idx level (tree_node_idx n) const noexcept
Level of node n.
auto neighbors (tree_node_idx n) const noexcept
All neighbors (across all manifolds) of node n.
template<typename Manifold >
auto neighbors (tree_node_idx n, Manifold manifold) const noexcept
All neighbors across manifold of node n.
template<typename NeighborPos , typename Manifold = get_tag_t<NeighborPos>>
point_t coordinates (tree_node_idx n, NeighborPos p) const noexcept
Center coordinates of neighbor p of node n.
Additional Inherited Members
Static Public Member Functions inherited from hm3::tree::tree< Nd >
static constexpr int_t dimension () noexcept
Number of spatial dimensions of the tree.
static constexpr auto dimensions () noexcept
Range of spatial dimensions of the tree: [0, Nd)
Public Attributes inherited from hm3::tree::tree< Nd >
siblings_idx sg_capacity_ = 0_sg
Sibling group capacity: maximum number of sibling groups that the tree can store.
std::unique_ptr< node_idx[]> parents_ = nullptr
Indices to the parent node of each sibling group (1 index / sibling group)
std::unique_ptr< node_idx[]> first_children_ = nullptr
Indices of the first children of each node (1 index / node)
node_idx size_ = 0_n
Number of nodes in the tree.
siblings_idx first_free_sibling_group_ {0}
First group of siblings that is free (i.e. not in use)
Member Function Documentation
template<uint_t Nd> template<typename NeighborPos , typename Manifold = get_tag_t<NeighborPos>> point_t hm3::grid::hc::single< Nd >::coordinates (tree_node_idx n, NeighborPos p) const noexcept
Center coordinates of neighbor p of node n.
Returns the correct coordinates even if:
neighbor does not exist
neighbor would lie outside of the bounding box
References hm3::grid::hc::single< Nd >::coordinates(), hm3::tree::tree< Nd >::dimensions(), and hm3::grid::hc::single< Nd >::length().