HM3: hm3::solver::square_structured_indices< Nd, Nic, Nhl > Struct Template Reference
hm3::solver::square_structured_indices< Nd, Nic, Nhl > Struct Template Reference
Description
template<uint_t Nd, uint_t Nic, uint_t Nhl>
struct hm3::solver::square_structured_indices< Nd, Nic, Nhl >
Structured grid indices and iteration.
Structured grid indices and iteration for square grid (same number of cells per dimension)
Nd: number of spatial dimensions Nic: number of internal cells per dimension Nhl: number of of halo layers
Inherited by hm3::solver::fv::block< Nd, Nv, Nic, Nhl >.
Instances and minimal complete definitions
struct index_t
Index: glbal tile index + coords.
static constexpr auto all () noexcept
External iterators.
static constexpr auto internal () noexcept
Internal cells.
static constexpr auto halo () noexcept
Halo cells.
static constexpr auto left_halos_1d () noexcept
1D Left-halos
static constexpr auto right_halos_1d () noexcept
1D Right-halos
static constexpr auto internal_1d () noexcept
1D Internal
static constexpr auto all_1d () noexcept
1D All
Construct indices
CONCEPT_REQUIRES (Nd==1) static const expr index_t from(coordinates_t ids) noexcept
Tile index from spatial coordinates.
CONCEPT_REQUIRES (Nd==2) static const expr index_t from(coordinates_t ids) noexcept
Tile index from spatial coordinates.
CONCEPT_REQUIRES (Nd==3) static index_t from(coordinates_t ids) noexcept
Tile index from spatial coordinates.
CONCEPT_REQUIRES (Nd==1) static const expr index_t from(suint_t idx) noexcept
Spatial coordinates from tile index.
CONCEPT_REQUIRES (Nd==2) static const expr index_t from(suint_t idx) noexcept
Spatial coordinates from tile index.
CONCEPT_REQUIRES (Nd==3) static const expr index_t from(suint_t idx) noexcept
Spatial coordinates from tile index.
CONCEPT_REQUIRES (Nd==1) static const expr index_t from(coordinates_t ids) noexcept
Tile index from spatial coordinates.
CONCEPT_REQUIRES (Nd==2) static const expr index_t from(coordinates_t ids) noexcept
Tile index from spatial coordinates.
CONCEPT_REQUIRES (Nd==3) static index_t from(coordinates_t ids) noexcept
Tile index from spatial coordinates.
CONCEPT_REQUIRES (Nd==1) static const expr index_t from(suint_t idx) noexcept
Spatial coordinates from tile index.
CONCEPT_REQUIRES (Nd==2) static const expr index_t from(suint_t idx) noexcept
Spatial coordinates from tile index.
CONCEPT_REQUIRES (Nd==3) static const expr index_t from(suint_t idx) noexcept
Spatial coordinates from tile index.
template<typename Function >
static constexpr void for_each (Function &&f) noexcept
Internal iterators.
template<typename Function , CONCEPT_REQUIRES_(Nd==3) >
static constexpr void for_each_halo (Function &&f) noexcept
static constexpr auto all () noexcept
External iterators.
static constexpr auto internal () noexcept
Internal cells.
static constexpr auto halo () noexcept
Halo cells.
static constexpr auto left_halos_1d () noexcept
1D Left-halos
static constexpr auto right_halos_1d () noexcept
1D Right-halos
static constexpr auto internal_1d (uint_t h=0) noexcept
1D Internal
static constexpr auto all_1d () noexcept
1D All
template<typename Function >
static constexpr void for_each (Function &&f) noexcept
Internal iterators.
template<typename Function , CONCEPT_REQUIRES_(Nd==3) >
static constexpr void for_each_halo (Function &&f) noexcept
Public Types
using coordinates_t = std::array< suint_t, Nd >
Coordinates e.g. {i, j, k}.
using coordinates_t = std::array< suint_t, Nd >
Coordinates e.g. {i, j, k}.
Static Public Member Functions
static constexpr suint_t dimension () noexcept
Spatial dimension.
static constexpr auto dimensions () noexcept
Range of spatial dimensions.
static constexpr suint_t halo_layers () noexcept
Number of halo layers.
static constexpr suint_t internal_cells_per_length () noexcept
Number of internal cells per length.
static constexpr suint_t cells_per_length () noexcept
Number of cells per length.
static constexpr suint_t size () noexcept
Total number of cells.
static constexpr suint_t internal_begin () noexcept
First internal tile per length.
static constexpr suint_t internal_end () noexcept
One past last internal tile per length.
static constexpr suint_t left_halos_begin () noexcept
First halo tile left.
static constexpr suint_t left_halos_end () noexcept
One past last halo tile left.
static constexpr suint_t right_halos_begin () noexcept
First halo tile right.
static constexpr suint_t right_halos_end () noexcept
One past last halo tile right.
static constexpr bool is_internal (suint_t t) noexcept
Is tile t internal?
static constexpr bool is_halo (suint_t t) noexcept
Is tile t halo?
static constexpr index_t at (suint_t tile_idx, suint_t d, suint_t offset) noexcept
Tile at offest offset from tile tile_idx across dimension d TODO: slow but works.
static constexpr index_t at (suint_t tile_idx, coordinates_t offset) noexcept
Tile at offest offset from tile tile_idx across dimension d TODO: slow but works.
static constexpr suint_t dimension () noexcept
Spatial dimension.
static constexpr auto dimensions () noexcept
Range of spatial dimensions.
static constexpr suint_t halo_layers () noexcept
Number of halo layers.
static constexpr suint_t internal_cells_per_length () noexcept
Number of internal cells per length.
static constexpr suint_t cells_per_length () noexcept
Number of cells per length.
static constexpr suint_t size () noexcept
Total number of cells.
static constexpr suint_t internal_begin (uint_t h=0) noexcept
First internal tile per length.
static constexpr suint_t internal_end (uint_t h=0) noexcept
One past last internal tile per length.
static constexpr suint_t left_halos_begin () noexcept
First halo tile left.
static constexpr suint_t left_halos_end () noexcept
One past last halo tile left.
static constexpr suint_t right_halos_begin () noexcept
First halo tile right.
static constexpr suint_t right_halos_end () noexcept
One past last halo tile right.
static constexpr bool is_internal (suint_t t) noexcept
Is tile t internal?
static constexpr bool is_halo (suint_t t) noexcept
Is tile t halo?
static constexpr index_t at (index_t i, suint_t d, suint_t offset) noexcept
Tile at offest offset from tile tile_idx across dimension d TODO: slow but works.
static constexpr index_t at (suint_t idx, coordinates_t offset) noexcept
Tile at offest offset from tile tile_idx across dimension d TODO: slow but works.
Member Function Documentation
template<uint_t Nd, uint_t Nic, uint_t Nhl> static constexpr auto hm3::solver::square_structured_indices< Nd, Nic, Nhl >::all () static noexcept
External iterators.
Total range of cells
References hm3::solver::square_structured_indices< Nd, Nic, Nhl >::size().
Referenced by hm3::solver::square_structured_indices< Nd, Nic, Nhl >::for_each(), hm3::solver::square_structured_indices< Nd, Nic, Nhl >::halo(), and hm3::solver::square_structured_indices< Nd, Nic, Nhl >::internal().
template<uint_t Nd, uint_t Nic, uint_t Nhl> template<typename Function , CONCEPT_REQUIRES_(Nd==3) > static constexpr void hm3::solver::square_structured_indices< Nd, Nic, Nhl >::for_each_halo (Function && f) static noexcept
front:
back:
bottom:
top:
side left:
side right:
References hm3::solver::square_structured_indices< Nd, Nic, Nhl >::all_1d(), hm3::solver::square_structured_indices< Nd, Nic, Nhl >::internal_1d(), hm3::solver::square_structured_indices< Nd, Nic, Nhl >::left_halos_1d(), and hm3::solver::square_structured_indices< Nd, Nic, Nhl >::right_halos_1d().
template<uint_t Nd, uint_t Nic, uint_t Nhl> static constexpr auto hm3::solver::square_structured_indices< Nd, Nic, Nhl >::all () static noexcept
External iterators.
Total range of cells
References hm3::solver::square_structured_indices< Nd, Nic, Nhl >::size().
template<uint_t Nd, uint_t Nic, uint_t Nhl> template<typename Function , CONCEPT_REQUIRES_(Nd==3) > static constexpr void hm3::solver::square_structured_indices< Nd, Nic, Nhl >::for_each_halo (Function && f) static noexcept
front:
back:
bottom:
top:
side left:
side right:
References hm3::solver::square_structured_indices< Nd, Nic, Nhl >::all_1d(), hm3::solver::square_structured_indices< Nd, Nic, Nhl >::internal_1d(), hm3::solver::square_structured_indices< Nd, Nic, Nhl >::left_halos_1d(), and hm3::solver::square_structured_indices< Nd, Nic, Nhl >::right_halos_1d().